
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1YWRkMDU5OTQ3OGI0ZjFiNDVlNTVkYzYiLCJpYXQiOjE1MjQ1MDcwNjB9.BSEc319c-5VnbOuwonC5BZuf4fg5lNW39WNdx-USTGg

{
	"title": "A Midsummer Night's Dream",
	"author": "Shakespeare",
	"url" : "http://altavista.com221",
	"likes": 15,
	"userId" : "5add0599478b4f1b45e55dc6"
}